version: '3'
services:
  backend:
    image: eal-backend
    container_name: eal-backend
    ports:
      - "8080:8080"

  frontend:
    image: eal-frontend
    container_name: eal-frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend

