version: '3'
services:
  backend:
    image: eal-backend
    container_name: eal-backend
    ports:
      - "8081:8081"
    networks:
      - eal-network

  frontend:
    image: eal-frontend
    container_name: eal-frontend
    ports:
      - "8080:8080"
    networks:
      - eal-network
    depends_on:
      - backend

networks:
  eal-network:
    driver: bridge
